apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aics-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  rules:
    - host: aics.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aics-api
                port:
                  number: 80
