apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-deployment.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: aics
  app.kubernetes.io/part-of: customer-support
